version: "3.9"
services:
  backend1:
    build:
      context: .  # Usa o diretório raiz como contexto
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_DB_TYPE=postgres
      - FLASK_DB_USER=postgres
      - FLASK_DB_NAME=guess_game
      - FLASK_DB_PASSWORD=secretpass
      - FLASK_DB_HOST=postgres
      - FLASK_DB_PORT=5432
    depends_on:
      - postgres
    restart: always
    networks:
      - app_network

  backend2:
    build:
      context: .  # Usa o diretório raiz como contexto
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_DB_TYPE=postgres
      - FLASK_DB_USER=postgres
      - FLASK_DB_NAME=guess_game
      - FLASK_DB_PASSWORD=secretpass
      - FLASK_DB_HOST=postgres
      - FLASK_DB_PORT=5432
    depends_on:
      - postgres
    restart: always
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
      - frontend
    restart: always
    networks:
      - app_network

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: guess_game
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app_network
volumes:
  postgres_data:

networks:
  app_network:
