version: "3.9"
services:
  backend1: # Primeira instância do backend
    build: ./backend
    ports:
      - "5001:5000" # Porta diferente para cada instância
    environment:
      - FLASK_APP=run.py
      - FLASK_DB_TYPE=postgres
      - FLASK_DB_USER=postgres
      - FLASK_DB_NAME=guess_game
      - FLASK_DB_PASSWORD=postgres
      - FLASK_DB_HOST=db
    depends_on:
      - db
    restart: always  # Política de reinício

  backend2: # Segunda instância do backend
    build: ./backend
    ports:
      - "5002:5000" # Porta diferente para cada instância
    environment:
      - FLASK_APP=run.py
      - FLASK_DB_TYPE=postgres
      - FLASK_DB_USER=postgres
      - FLASK_DB_NAME=guess_game
      - FLASK_DB_PASSWORD=postgres
      - FLASK_DB_HOST=db
    depends_on:
      - db
    restart: always  # Política de reinício


  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    restart: always  # Política de reinício

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=guess_game
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always  # Política de reinício

volumes:
  pgdata: